### ISSUE TITLE
Ali – The Busy Professional

### ISSUE THREAD

**Issue by Carlos-n21** [Carlos-n21/js-game-group-project#14]
User Story: Ali Ahmed, 40 years, IT Manager, has been living in the UK for 5 years and needs to pass the Life in the UK test to apply for British citizenship. Aims to efficiently prepare for the test alongside a busy work schedule.
Wants to find resources that look straightforward and time-efficient, so that he can practice for the test.
Has no problems using different technologies to study and prefers to do this on his tablet during his commute or at home on the desktop.
Finds it difficult to find a high-quality, time-efficient study tool that can be adapted to his work schedule and family time, whilst keeping him motivated. 

**Acceptance Criteria:**

- [ ] A clean, professional interface with minimal distractions.
- [ ] Time-efficient quizzes that can be completed quickly.
- [ ] Summarized feedback and performance analytics.

**Tasks:**

- [ ] Create a modern and appealing design
- [ ] Make a quick quiz that can be completed under 1minute
- [ ] Provide the option to do a new quiz or retry it
